In [1]:
import numpy as np

In [5]:
#Arthmetic operations on 1-D arrays:

In [33]:
#addition:

arr1 = np.array([41,68,49,65,22])
arr2 = np.array([83,36,23,99,14])
print(arr1+arr2)
print(np.add(arr1,arr2))

[124 104  72 164  36]
[124 104  72 164  36]


In [31]:
#substraction:
arr1 = np.array([31,887,44,53,72])
arr2 = np.array([573,786,27,29,91])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[-542  101   17   24  -19]
[-542  101   17   24  -19]


In [19]:
#multiplication:

arr1 = np.array([1,8,4,5,2])
arr2 = np.array([3,6,2,9,1])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[ 3 48  8 45  2]
[ 3 48  8 45  2]


In [29]:
#division:
arr1 = np.array([51,58,64,57,23])
arr2 = np.array([32,66,23,69,156])
n= 6
print(arr1/arr2)
print(arr1/n)
print(n/arr2)
print(np.divide(arr1,arr2))

[1.59375    0.87878788 2.7826087  0.82608696 0.1474359 ]
[ 8.5         9.66666667 10.66666667  9.5         3.83333333]
[0.1875     0.09090909 0.26086957 0.08695652 0.03846154]
[1.59375    0.87878788 2.7826087  0.82608696 0.1474359 ]


In [36]:
# square root:

arr1 = np.array([45,85,64,45,62])
arr2 = np.array([33,34,28,92,15])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[6.70820393 9.21954446 8.         6.70820393 7.87400787]
[5.74456265 5.83095189 5.29150262 9.59166305 3.87298335]


In [42]:
#floor division:
arr1 = np.array([45,89,45,89,90])
arr1 = np.array([45,76,34,67,56])
n =3
print(arr1//arr2)
print(arr1//n)
print(n//arr2)
print(np.floor_divide(arr1,arr2))

[1 2 1 0 3]
[15 25 11 22 18]
[0 0 0 0 0]
[1 2 1 0 3]


In [44]:
#modulus:

arr1 = np.array([4,9,5,8,9])
arr1 = np.array([8,9,4,7,6])
n =3
print(arr1%arr2)
print(arr1%n)
print(n%arr2)
print(np.mod(arr1,arr2))

[8 9 4 7 6]
[2 0 1 1 0]
[3 3 3 3 3]
[8 9 4 7 6]


In [48]:
#Exponential:

arr1 = np.array([4,9,5,8,9])
print(arr1**5)

[ 1024 59049  3125 32768 59049]


In [ ]:
#Arthmetic operations on 2-D arrays:

In [50]:
#addition
arr1 = np.array([[41,68,49,65,22],[64,78,45,90,23]])
arr2 = np.array([[83,36,23,99,14],[45,67,23,67,23]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[124 104  72 164  36]
 [109 145  68 157  46]]
[[124 104  72 164  36]
 [109 145  68 157  46]]


In [52]:
#subtaction:

arr1 = np.array([[31,887,44,53,72],[67,34,23,67,89]])
arr2 = np.array([[573,786,27,29,91],[56,90,78,56,23]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[-542  101   17   24  -19]
 [  11  -56  -55   11   66]]
[[-542  101   17   24  -19]
 [  11  -56  -55   11   66]]


In [54]:
#multiplication:

arr1 = np.array([[1,8,4,5,2],[3,7,5,6,8]])
arr2 = np.array([[3,6,2,9,1],[6,9,0,3,1]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[ 3 48  8 45  2]
 [18 63  0 18  8]]
[[ 3 48  8 45  2]
 [18 63  0 18  8]]


In [56]:
#division:
arr1 = np.array([[51,58,64,57,23],[34,67,23,12,15]])
arr2 = np.array([[32,66,23,69,156],[43,5,78,98,12]])
n= 6
print(arr1/arr2)
print(arr1/n)
print(n/arr2)
print(np.divide(arr1,arr2))

[[ 1.59375     0.87878788  2.7826087   0.82608696  0.1474359 ]
 [ 0.79069767 13.4         0.29487179  0.12244898  1.25      ]]
[[ 8.5         9.66666667 10.66666667  9.5         3.83333333]
 [ 5.66666667 11.16666667  3.83333333  2.          2.5       ]]
[[0.1875     0.09090909 0.26086957 0.08695652 0.03846154]
 [0.13953488 1.2        0.07692308 0.06122449 0.5       ]]
[[ 1.59375     0.87878788  2.7826087   0.82608696  0.1474359 ]
 [ 0.79069767 13.4         0.29487179  0.12244898  1.25      ]]


In [58]:
# square root:

arr1 = np.array([[45,85,64,45,62],[67,87,34,12,67]])
arr2 = np.array([[33,34,28,92,15],[78,98,56,34,18]])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[[6.70820393 9.21954446 8.         6.70820393 7.87400787]
 [8.18535277 9.32737905 5.83095189 3.46410162 8.18535277]]
[[5.74456265 5.83095189 5.29150262 9.59166305 3.87298335]
 [8.83176087 9.89949494 7.48331477 5.83095189 4.24264069]]


In [60]:
#floor division:
arr1 = np.array([[45,89,45,89,90],[98,76,57,83,45]])
arr1 = np.array([[45,76,34,67,56],[42,92,75,34,71]])
n =3
print(arr1//arr2)
print(arr1//n)
print(n//arr2)
print(np.floor_divide(arr1,arr2))

[[1 2 1 0 3]
 [0 0 1 1 3]]
[[15 25 11 22 18]
 [14 30 25 11 23]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1 2 1 0 3]
 [0 0 1 1 3]]


In [62]:
#modulus:

arr1 = np.array([[4,9,5,8,9],[6,8,2,1,7]])
arr1 = np.array([[8,9,4,7,6],[7,4,2,7,3]])
n =3
print(arr1%arr2)
print(arr1%n)
print(n%arr2)
print(np.mod(arr1,arr2))

[[8 9 4 7 6]
 [7 4 2 7 3]]
[[2 0 1 1 0]
 [1 1 2 1 0]]
[[3 3 3 3 3]
 [3 3 3 3 3]]
[[8 9 4 7 6]
 [7 4 2 7 3]]


In [64]:
#Exponential:

arr1 = np.array([[4,9,5,8,9],[5,8,3,2,7]])
print(arr1**5)

[[ 1024 59049  3125 32768 59049]
 [ 3125 32768   243    32 16807]]


In [ ]:
#Arthmetic operations on 3-D arrays:

In [66]:
#addition
arr1 = np.array([[[41,68,49,65,22],[64,78,45,90,23]],
                 [[45,62,78,12,41],[56,89,34,56,23]],
                 [[46,78,56,23,12],[89,67,34,54,65]]]
                )
arr2 = np.array([[[83,36,23,99,14],[45,67,23,67,23]],
                 [[78,95,63,34,45],[67,34,23,13,15]],
                 [[89,56,34,76,83],[56,72,34,90,56]]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[[124 104  72 164  36]
  [109 145  68 157  46]]

 [[123 157 141  46  86]
  [123 123  57  69  38]]

 [[135 134  90  99  95]
  [145 139  68 144 121]]]
[[[124 104  72 164  36]
  [109 145  68 157  46]]

 [[123 157 141  46  86]
  [123 123  57  69  38]]

 [[135 134  90  99  95]
  [145 139  68 144 121]]]


In [68]:
#subtaction:

arr1 = np.array([[[177,758,759,585,872],[754,673,876,896,765]],
                 [[465,234,348,223,134],[634,234,894,786,897]],
                 [[676,788,236,385,245],[923,987,567,345,345]]]
                )
arr2 = np.array([[[83,36,23,99,14],[45,67,23,67,23]],
                 [[78,95,63,34,45],[67,34,23,13,15]],
                 [[89,56,34,76,83],[56,72,34,90,56]]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[[ 94 722 736 486 858]
  [709 606 853 829 742]]

 [[387 139 285 189  89]
  [567 200 871 773 882]]

 [[587 732 202 309 162]
  [867 915 533 255 289]]]
[[[ 94 722 736 486 858]
  [709 606 853 829 742]]

 [[387 139 285 189  89]
  [567 200 871 773 882]]

 [[587 732 202 309 162]
  [867 915 533 255 289]]]


In [70]:
#multiplication:

arr1 = np.array([[[177,758],[896,765]],
                 [[465,234],[786,897]],
                 [[676,788],[345,345]]]
                )
arr2 = np.array([[[99,14],[45,67]],
                 [[34,45],[67,15]],
                 [[76,83],[56,56]]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[[17523 10612]
  [40320 51255]]

 [[15810 10530]
  [52662 13455]]

 [[51376 65404]
  [19320 19320]]]
[[[17523 10612]
  [40320 51255]]

 [[15810 10530]
  [52662 13455]]

 [[51376 65404]
  [19320 19320]]]


In [74]:
#division:
arr1 = np.array([[[758,759,585],[767,896,765]],
                 [[465,348,223],[894,786,897]],
                 [[676,236,385],[967,345,345]]]
                )
arr2 = np.array([[[783,336,234],[645,647,233]],
                 [[878,895,635],[267,324,263]],
                 [[789,156,343],[556,222,34]]])
n= 5
print(arr1/arr2)
print(arr1/n)
print(n/arr2)
print(np.divide(arr1,arr2))

[[[ 0.96807152  2.25892857  2.5       ]
  [ 1.18914729  1.38485317  3.2832618 ]]

 [[ 0.52961276  0.38882682  0.3511811 ]
  [ 3.34831461  2.42592593  3.41064639]]

 [[ 0.85678074  1.51282051  1.12244898]
  [ 1.73920863  1.55405405 10.14705882]]]
[[[151.6 151.8 117. ]
  [153.4 179.2 153. ]]

 [[ 93.   69.6  44.6]
  [178.8 157.2 179.4]]

 [[135.2  47.2  77. ]
  [193.4  69.   69. ]]]
[[[0.0063857  0.01488095 0.02136752]
  [0.00775194 0.00772798 0.02145923]]

 [[0.00569476 0.00558659 0.00787402]
  [0.01872659 0.0154321  0.01901141]]

 [[0.00633714 0.03205128 0.01457726]
  [0.00899281 0.02252252 0.14705882]]]
[[[ 0.96807152  2.25892857  2.5       ]
  [ 1.18914729  1.38485317  3.2832618 ]]

 [[ 0.52961276  0.38882682  0.3511811 ]
  [ 3.34831461  2.42592593  3.41064639]]

 [[ 0.85678074  1.51282051  1.12244898]
  [ 1.73920863  1.55405405 10.14705882]]]


In [76]:
# square root:

arr1 = np.array([[[78,79,58],[76,86,75]],
                 [[46,33,22],[89,76,87]],
                 [[67,26,38],[96,35,35]]]
                )
arr2 = np.array([[[73,36,24],[64,47,24]],
                 [[88,95,65],[26,24,63]],
                 [[79,16,43],[55,22,34]]])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[[[8.83176087 8.88819442 7.61577311]
  [8.71779789 9.2736185  8.66025404]]

 [[6.78232998 5.74456265 4.69041576]
  [9.43398113 8.71779789 9.32737905]]

 [[8.18535277 5.09901951 6.164414  ]
  [9.79795897 5.91607978 5.91607978]]]
[[[8.54400375 6.         4.89897949]
  [8.         6.8556546  4.89897949]]

 [[9.38083152 9.74679434 8.06225775]
  [5.09901951 4.89897949 7.93725393]]

 [[8.88819442 4.         6.55743852]
  [7.41619849 4.69041576 5.83095189]]]


In [80]:
#floor division:
arr1 = np.array([[[8,7,58],[6,6,5]],
                 [[4,3,22],[8,6,7]],
                 [[6,2,38],[9,5,3]]]
                )
arr2 = np.array([[[7,6,2],[4,4,4]],
                 [[8,5,6],[6,4,3]],
                 [[7,1,4],[5,2,4]]])
n =2
print(arr1//arr2)
print(arr1//n)
print(n//arr2)
print(np.floor_divide(arr1,arr2))

[[[ 1  1 29]
  [ 1  1  1]]

 [[ 0  0  3]
  [ 1  1  2]]

 [[ 0  2  9]
  [ 1  2  0]]]
[[[ 4  3 29]
  [ 3  3  2]]

 [[ 2  1 11]
  [ 4  3  3]]

 [[ 3  1 19]
  [ 4  2  1]]]
[[[0 0 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 2 0]
  [0 1 0]]]
[[[ 1  1 29]
  [ 1  1  1]]

 [[ 0  0  3]
  [ 1  1  2]]

 [[ 0  2  9]
  [ 1  2  0]]]


In [82]:
#modulus:

arr1 = np.array([[[75,79,58],[76,86,75]],
                 [[44,13,22],[89,56,87]],
                 [[61,86,38],[96,35,35]]]
                )
arr2 = np.array([[[71,36,24],[64,47,24]],
                 [[78,95,65],[46,24,73]],
                 [[89,16,43],[55,42,34]]])
n =3
print(arr1%arr2)
print(arr1%n)
print(n%arr2)
print(np.mod(arr1,arr2))

[[[ 4  7 10]
  [12 39  3]]

 [[44 13 22]
  [43  8 14]]

 [[61  6 38]
  [41 35  1]]]
[[[0 1 1]
  [1 2 0]]

 [[2 1 1]
  [2 2 0]]

 [[1 2 2]
  [0 2 2]]]
[[[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]]]
[[[ 4  7 10]
  [12 39  3]]

 [[44 13 22]
  [43  8 14]]

 [[61  6 38]
  [41 35  1]]]


In [86]:
#Exponential:

arr1 = np.array([[[7,8],[8,5]],
                 [[5,2],[6,7]],
                 [[6,8],[5,345]]])
print(arr1**4)

[[[  981506241  -588691696]
  [  268435456 -1109083055]]

 [[ -491389631 -1296747760]
  [ -580191728 -1144418815]]

 [[-1626332928  -975605504]
  [ 1282048737  1282048737]]]
