In [1]:
#NumPy

!pip install numpy

In [3]:
#importing numpy
import numpy as np

#creating numpy
a = np.array([1,2,3,4, 5])
b = np.array([(1.5, 2.7, 5.3), (46,35,6)])
c = np.array([[(1.5, 7.2,3),(5.4,5,6)],[(7.,9.2,1),(4,5,6.8)]])
print(a)
print(b)
print(c)

[1 2 3 4 5]
[[ 1.5  2.7  5.3]
 [46.  35.   6. ]]
[[[1.5 7.2 3. ]
  [5.4 5.  6. ]]

 [[7.  9.2 1. ]
  [4.  5.  6.8]]]


In [39]:
#initial place holders

#creating an array of zeros

np.zeros((4,8)) #creating 2D array #3 rows and 4 columns

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
#creating an array of ones

np.ones((2,4,4)) #shape, rows, cols

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [45]:
#creating an array of evenly spaced values(step value)
d = np.arange(5,25,4) #steps n-1(3-1 = 2)
print(d)

[ 5  9 13 17 21]


In [19]:
#creating an array of evenly spaced values(number of samples)
np.linspace(6,96,8)

array([ 6.        , 18.85714286, 31.71428571, 44.57142857, 57.42857143,
       70.28571429, 83.14285714, 96.        ])

In [49]:
#create a constant array
#create a 1D array

e= np.full((9),5) #columns
print(e)
print(e.ndim)

[5 5 5 5 5 5 5 5 5]
1


In [51]:
#create a 2D array

e= np.full((2,3),63) #columns
print(e)
print(e.ndim)

[[63 63 63]
 [63 63 63]]
2


In [55]:
#create a 3D array

e= np.full((3,3,4),6) #columns
print(e)
print("No of Dimensions:",e.ndim)

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]
No of Dimensions: 3


In [29]:
e= np.full((2,6),6) #columns
print(e)
print("No of Dimensions:",e.ndim)

[[6 6 6 6 6 6]
 [6 6 6 6 6 6]]
No of Dimensions: 2


In [27]:
#creating a 2*2 identity matrix

f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#creating an array with random values
np.random.random((2,3))

array([[0.599327  , 0.65277708, 0.96759145],
       [0.39591454, 0.42499582, 0.44086044]])

In [63]:
np.random.randint(5,10)

6

In [67]:
#to find the shape of an array.
arr = np.array([[1,5,6],[5,3,6],[93,7,3],[0,2,5]])
print(arr.shape)

(4, 3)


In [69]:
#To find no of elements in array
arr = np.array([[1,2,2,6],[6,2,7,2],[4,7,2,8]])
print(arr.size)

12


In [71]:
#to find the length of array
arr = np.array([[5,7,3,7],[6,7,2,8],[7,9,2,5],[2,8,3,4]])
len(arr)

4

In [ ]:
#Access array elements:

you can access an array element by referring to its index number.
The indexes in NumPy array start with 0.
Meaning that the firdt element has index 0.

In [13]:
arr =np.array([1,2,3,4,5,6])
print(arr[2])
print(arr[5])

3
6


In [21]:
#adding two index position.

arr = np.array([1,6,5,2,6,3])
print(arr[2]-arr[5]-arr[4])
print(arr[5]+arr[3]+arr[2])
print(arr[4]*arr[3])

-4
10
12


In [25]:
#Access 2-D arrays
#access the element on the first row , second column
arr = np.array([[1,6,7,3,2],[6,9,4,2,8],[5,2,7,8,4],[1,9,3,2,8]])
print('4nd element on 3rd row:', arr[3,4])

4nd element on 3rd row: 8


In [33]:
arr = np.array([[2,7,8],[9,3,4],[5,3,4]])
print('2nd element on 2nd row:', arr[2,2])

2nd element on 2nd row: 4


In [45]:
#Access 3-D Arrays
arr = np.array([[[1,2,3],
                 [4,5,6]],
                [[1,23,5],
                 [4,76,89]],
                [[1,56,3],
                 [4,67,34]],
                [[5,65,2],
                 [5,77,32]]])

#Access by index
print(arr[3,1,1]) #([2d,1d,element])
print(arr[1,0,1])
print(arr[2,0,2])

77
23
3


In [ ]:
#Data Types

Datatypes in NumPy
NumPy has some extra data types and refer to data types with one character, like i for integers, u for unsigned integers etc.
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned(just like integers(whole numbers)but have the property that they dont have a + or - sign associated with them)
f - float
c - complex
M - datetime
O - Object
S - String

In [49]:
#checking the datatype
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [47]:
#string
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [53]:
#Create an array with data type 4 bytes integer:

arr = np.array([1, 6, 3, 3], dtype='i4')
print(arr)
print(arr.dtype)


[1 6 3 3]
int32


In [55]:
#Change data type from float to integer by using 'i' as parameter value:

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [63]:
#Change data type from float to integer by using int as parameter value:

arr = np.array([1.5, 4.1, 8.6])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 4 8]
int32


In [13]:
#Change data type from integer to boolean:

arr = np.array([1, 0, 3, 7, 0, 8])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True False  True]
bool


In [73]:
arr = np.array([1, 3, 0, 5])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True False  True]
bool


In [15]:
#changing into to float
arr = np.array([0,6,4,3,2])
x = arr.astype('f')
print(x)

[0. 6. 4. 3. 2.]


In [19]:
#changing float to unsigned integer
arr = np.array([0., 6.5, 4., 3.8, 2.6])
x = arr.astype('U')
print(x)

['0.0' '6.5' '4.0' '3.8' '2.6']


In [21]:
#changing int to unsigned integer
arr = np.array([1, 0, 3, 7, 0, 8])
x = arr.astype('U')
print(x)

['1' '0' '3' '7' '0' '8']


In [23]:
#changing float to complex float
arr = np.array([8.9, 3.6, 8.5, 9.7, 3.5])
x = arr.astype('c')
print(x)

[b'8' b'3' b'8' b'9' b'3']


In [27]:
#changing int to complex float
arr = np.array([1, 9, 6, 5, 3, 7])
x = arr.astype('c')
print(x)

[b'1' b'9' b'6' b'5' b'3' b'7']


In [75]:
#copy method: The copy SHOULD NOT be affected by the changes made to the original array.
#Make a copy, change the original array, and display both arrays:

arr = np.array([34, 6, 67, 46, 55])
x = arr.copy()
arr[0] =  768
print(arr)
print(x)

[768   6  67  46  55]
[34  6 67 46 55]


In [77]:
arr = np.array([74, 56, 75, 87, 5])
x = arr.copy()
arr[4] =  768
print(arr)
print(x)

[ 74  56  75  87 768]
[74 56 75 87  5]


In [79]:
#view method: The view SHOULD be affected by the changes made to the original array.
#Make a view, change the original array, and display both arrays:

arr = np.array([34, 6, 67, 46, 55])
x = arr.view()
arr[0] = 42

print(arr)
print(x)



[42  6 67 46 55]
[42  6 67 46 55]


In [89]:
#shape : The shape of an array is the number of elements in each dimension.
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [91]:
#Create an array with 3 dimensions using ndmin using a 1 dimension array
arr = np.array([1, 2, 3, 4], ndmin=3)
print(arr)
print('shape of array :', arr.shape)

[[[1 2 3 4]]]
shape of array : (1, 1, 4)


In [ ]:
#Reshaping arrays:

Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [29]:
#converting the following 1-D array with 12 elements into a 2-D array.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.size)
print(arr)
print("*************************************************************")
newarr = arr.reshape(2,6)
print(newarr)

12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
*************************************************************
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  5  3]
 [ 4  5  3]
 [ 6  8  8]
 [ 9 13 12]]


In [9]:
#Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [31]:
arr = np.array([5, 6, 3, 4, 5, 3, 7, 8, 8, 9, 13, 11, 8,6,9,5,0,3,2,1])
newarr = arr.reshape(5, 2, 2)
print(arr)
print("*************************************************************")
print(newarr)

[ 5  6  3  4  5  3  7  8  8  9 13 11  8  6  9  5  0  3  2  1]
*************************************************************
[[[ 5  6]
  [ 3  4]]

 [[ 5  3]
  [ 7  8]]

 [[ 8  9]
  [13 11]]

 [[ 8  6]
  [ 9  5]]

 [[ 0  3]
  [ 2  1]]]


In [37]:
#converting 2 -D array to 1 -D array
arr = np.array([[1,5,6],[4,7,9]])
x= arr.reshape(arr.size)
print(x)

[1 5 6 4 7 9]


In [55]:
#converting 2 - D to 3 - D array

arr = np.array([[1,5,6,4,5,3],[4,3,7,9,2,5],[4,1,2,6,3,1]])
print(arr.size)
x= arr.reshape(3,2,3)
print(x)
print("*************************************************************")
y= arr.reshape(3,3,2)
print(y)
print("*************************************************************")
z= arr.reshape(2,3,3)
print(z)

18
[[[1 5 6]
  [4 5 3]]

 [[4 3 7]
  [9 2 5]]

 [[4 1 2]
  [6 3 1]]]
*************************************************************
[[[1 5]
  [6 4]
  [5 3]]

 [[4 3]
  [7 9]
  [2 5]]

 [[4 1]
  [2 6]
  [3 1]]]
*************************************************************
[[[1 5 6]
  [4 5 3]
  [4 3 7]]

 [[9 2 5]
  [4 1 2]
  [6 3 1]]]


In [61]:
#converting 3-D array to 1-D array
arr = np.array([[[1,4,5],[3,6,4]],
                [[3,7,6],[4,6,2]],
                [[6,7,3],[9,6,0]]])
print(arr.size)
print(arr)
print("*************************************************************")
x= arr.reshape(arr.size)
print(x)


18
[[[1 4 5]
  [3 6 4]]

 [[3 7 6]
  [4 6 2]]

 [[6 7 3]
  [9 6 0]]]
*************************************************************
[1 4 5 3 6 4 3 7 6 4 6 2 6 7 3 9 6 0]


In [67]:
#converting 3-D array to 2-D array
arr = np.array([[[1,4,5],[3,6,4]],
                [[3,7,6],[4,6,2]],
                [[6,7,3],[9,6,0]]])
print(arr.size)
print(arr)
print("*************************************************************")
x= arr.reshape(3,6)
print(x)

18
[[[1 4 5]
  [3 6 4]]

 [[3 7 6]
  [4 6 2]]

 [[6 7 3]
  [9 6 0]]]
*************************************************************
[[1 4 5 3 6 4]
 [3 7 6 4 6 2]
 [6 7 3 9 6 0]]


In [75]:
#python program to create a datatype object

x= np.array([[1,2],[3,4]], dtype =np.float64)
print(x)
print("****************")
y = np.array([[5,6],[7,8]], dtype = np.float64)
print(y)

[[1. 2.]
 [3. 4.]]
****************
[[5. 6.]
 [7. 8.]]


In [ ]:
#sorting arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [77]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [79]:
arr = np.array([[[1,4,5],[3,6,4]],
                [[3,7,6],[4,6,2]],
                [[6,7,3],[9,6,0]]])
print(np.sort(arr))

[[[1 4 5]
  [3 4 6]]

 [[3 6 7]
  [2 4 6]]

 [[3 6 7]
  [0 6 9]]]


In [ ]:
#SLicing arrays:
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [81]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [83]:
arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[3:8])

[4 5 3 6 8]


In [85]:
#Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [87]:
arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[6:])

[ 6  8  8  9 13 12]


In [89]:
#Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [91]:
arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[:8])

[1 5 3 4 5 3 6 8]


In [95]:
#Negative Slicing : Use the minus operator to refer to an index from the end

#Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[-7:-1])

[ 3  6  8  8  9 13]


In [99]:
#step : Use the step value to determine the step of the slicing
#Return every other element from index 1 to index 5:

arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[1:5:2])

[5 4]


In [103]:
#Return every other element from the entire array:


arr = np.array([1, 5, 3, 4, 5, 3, 6, 8, 8, 9, 13, 12])
print(arr[::2])

[ 1  3  5  6  8 13]


In [105]:
#Slicing 2-D Arrays:

#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [111]:
arr = np.array([[1,5,6,4,5,3],[4,3,7,9,2,5],[4,1,2,6,3,1]])
print(arr[0:3, 2:4])
print("*******************")
print(arr[:,:])

[[6 4]
 [7 9]
 [2 6]]
*******************
[[1 5 6 4 5 3]
 [4 3 7 9 2 5]
 [4 1 2 6 3 1]]


In [113]:
arr = np.array([[1,5,6,4,5,3],[4,3,7,9,2,5],[4,1,2,6,3,1]])
print(arr[0:2,3])
print(arr[0:6,1])

[4 9]
[5 3 1]


In [115]:
t = np.array([[2,4,6,2],[5,7,2,8],[9,4,2,4]])
print(t[0:4,2])

[6 2 2]


In [131]:
#slicing 3D arrays:

arr = np.array([[[1,4,5,6,7,8],[3,6,4,7,2,6]],
                [[3,7,6,8,4,5],[4,6,2,4,9,3]],
                [[6,7,3,7,8,9],[9,6,0,2,9,4]]])
print(arr[0,0:4,1:4])
print("**************")
print(arr[:,:,:])

[[4 5 6]
 [6 4 7]]
**************
[[[1 4 5 6 7 8]
  [3 6 4 7 2 6]]

 [[3 7 6 8 4 5]
  [4 6 2 4 9 3]]

 [[6 7 3 7 8 9]
  [9 6 0 2 9 4]]]
