In [1]:
#NumPy

!pip install numpy

In [37]:
#importing numpy
import numpy as np

#creating numpy
a = np.array([1,2,3,4, 5])
b = np.array([(1.5, 2.7, 5.3), (46,35,6)])
c = np.array([[(1.5, 7.2,3),(5.4,5,6)],[(7.,9.2,1),(4,5,6.8)]])
print(a)
print(b)
print(c)

[1 2 3 4 5]
[[ 1.5  2.7  5.3]
 [46.  35.   6. ]]
[[[1.5 7.2 3. ]
  [5.4 5.  6. ]]

 [[7.  9.2 1. ]
  [4.  5.  6.8]]]


In [39]:
#initial place holders

#creating an array of zeros

np.zeros((4,8)) #creating 2D array #3 rows and 4 columns

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
#creating an array of ones

np.ones((2,4,4)) #shape, rows, cols

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [45]:
#creating an array of evenly spaced values(step value)
d = np.arange(5,25,4) #steps n-1(3-1 = 2)
print(d)

[ 5  9 13 17 21]


In [47]:
#creating an array of evenly spaced values(number of samples)
np.linspace(0,96,7)

array([ 0., 16., 32., 48., 64., 80., 96.])

In [49]:
#create a constant array
#create a 1D array

e= np.full((9),5) #columns
print(e)
print(e.ndim)

[5 5 5 5 5 5 5 5 5]
1


In [51]:
#create a 2D array

e= np.full((2,3),63) #columns
print(e)
print(e.ndim)

[[63 63 63]
 [63 63 63]]
2


In [55]:
#create a 3D array

e= np.full((3,3,4),6) #columns
print(e)
print("No of Dimensions:",e.ndim)

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]
No of Dimensions: 3


In [31]:
#creating a 2*2 identity matrix

f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
#creating an array with random values
np.random.random((2,3))

array([[0.599327  , 0.65277708, 0.96759145],
       [0.39591454, 0.42499582, 0.44086044]])

In [63]:
np.random.randint(5,10)

6

In [67]:
#to find the shape of an array.
arr = np.array([[1,5,6],[5,3,6],[93,7,3],[0,2,5]])
print(arr.shape)

(4, 3)


In [69]:
#To find no of elements in array
arr = np.array([[1,2,2,6],[6,2,7,2],[4,7,2,8]])
print(arr.size)

12


In [ ]:
#to find the length of array
arr = np.array([[5,7,3,7],[6,7,2,8],[7[